import Head from 'next/head'
import Layout from '@components/layout'
import SingleProduct from '@components/SingleProduct'

export async function getStaticPaths() {
    const products = await fetch("https://diplom-e-commerce-server.onrender.com/api/auth/catalog");

    const data = await products.json();
    const paths = data.products.map((item: any) => ({
        params: {
            id: item._id
        }
    }));
    return {
        paths,
        fallback: "blocking"
    };
  }

export async function getStaticProps(context: any) {
    const { params } = context;

    const product = await fetch(`https://diplom-e-commerce-server.onrender.com/api/auth/product/${params.id}`);

    const data = await product.json();

    return {
        props: {
            product: data
        },
        revalidate: 60,
    }
}

export default function SingleProductPage({ product }: any) {
    return (
        <>
            <Head>
              <title>{product.product.title}</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <SingleProduct product={product.product}/>
            </Layout>
        </>
    )
}
