import Head from 'next/head'
import Layout from '@components/layout'
import Cart from '@components/Cart'

export default function Home() {
    return (
        <>
            <Head>
              <title>Корзина товаров</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <Cart />
            </Layout>
        </>
    )
}